global using System.Xml.Linq;
global using CommonBasicLibraries.CollectionClasses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using AOEOTechEditorLibrary.Models;
global using Microsoft.AspNetCore.Components;
global using AOEOCivilizationLibrary.Constants;
global using uu1 = AOEOBasicDataLibrary.Helpers.UnitGroupConstants;
global using AOEOBasicDataLibrary.Helpers;
global using AOEOTechEditorLibrary.Interfaces;
global using AOEOTechEditorLibrary.Conditions;
