global using System.Xml.Linq;
global using CommonBasicLibraries.CollectionClasses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using AOEOTechEditorLibrary.Effects;
global using Microsoft.AspNetCore.Components;
global using AOEOCivilizationLibrary.Constants;
global using uu1 = AOEOBasicDataLibrary.Helpers.UnitGroupConstants;
global using AOEOBasicDataLibrary.Helpers;
global using AOEOTechEditorLibrary.Interfaces;
global using AOEOTechEditorLibrary.Prereqs;
global using kk1 = CommonBasicLibraries.TextProcessing.KeyValuePairHelpers.BasicKeyValueSerialization;
global using System.Text;
global using AOEOTechEditorLibrary.Shared;
global using AOEOTechEditorLibrary.Techs;
global using dd1 = AOEOBasicDataLibrary.Helpers.BasicGameLocationHelpers;